name: Docker Build and Push

on:
  push:
    tags:
      - '*'  # 모든 태그에 대해 이 워크플로우를 트리거합니다.
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: arn:aws:iam::654654416925:role/ljh-from-github-to-ecr-role

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: echo image tag
      run: echo $IMAGE_TAG

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Kustomize Resources
      run: |
        # kustomize 리소스 레포지토리 클론
        git clone git@github.com:jh-lee99/ljh-was-login.git
        cd ljh-was-login
        
        # base/kustomization.yaml 파일 수정
        sed -i "s|public.ecr.aws/d7s1z6u6/ljh-was-login:latest|${{ steps.login-ecr.outputs.registry }}/ljh-was-login:${{ env.IMAGE_TAG }}|g" echoserver-deployment.yaml
        
        # 변경 사항 커밋 및 푸시
        git config user.name "jh-lee99"
        git config user.email "jun99h1219@gmail.com"
        git add echoserver-deployment.yaml
        git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
        git push origin main
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_ECR_REPO }}:${{ env.IMAGE_TAG }}
